### ISSUE TITLE
Failed to start Permission denied: '/dev/log'

### ISSUE THREAD

**Issue by zanardo33** [eea/eea.docker.graylog2#5]
Hi,

I can't start your container, the first run of eeacms/graylog2:1.3.4.1 or eeacms/graylog2:2.0.3
make the same error message:

"syslog service cannot be started: [Errno 13] Permission denied: '/dev/log'"

command line run

docker run -d --name="Graylog" --privileged=true -v /docker/graylog:/data:rw -v /docker/graylog:/config:rw -p 9000:9000 -p 12900:12900 -p 12201:12201 eeacms/graylog2:1.3.4.1

how can i fix it ?

**Comment by avoinea** [comment]
Are you sure that your container is not up-and-running? That's usually a warning generated by [chaperone](https://github.com/garywiz/chaperone) because we use it without root privileges within container.

**Comment by sorenroug** [comment]
Could this be an SELinux problem? Do you have SELinux set to enforcing?

**Comment by zanardo33** [comment]
Thank you for your reply
The container is down, you can show full log

18:42:09 syslog service cannot be started: [Errno 13] Permission denied: '/dev/log' stderr
18:42:09 command service cannot be started: [Errno 13] Permission denied stderr
18:43:41 system startup cancelled due to error: greylog2.service did not find pid file '/tmp/graylog.pid' before 90sec process_timeout expired stderr
18:43:42 Request made to kill system. stderr

I'm using docker 1.6.2-0036 on synology  DSM 5.2-5644

**Comment by zanardo33** [comment]
I do not know SELinux, there have synology on ?

**Comment by ekulos** [comment]
The errors:
"""
18:42:09 syslog service cannot be started: [Errno 13] Permission denied: '/dev/log' stderr
18:42:09 command service cannot be started: [Errno 13] Permission denied stder
"""
are raised by chaperone that can't access to /dev/log, ignore it.

The system can't start because Graylog has some dependencies, it needs a elasticsearch server and a mongodb server (see https://github.com/eea/eea.docker.graylog2#dependencies).

Therefore you need to start these apps before the Graylog:

```
# Run MongoDB
$ docker run --name some-mongo -d mongo
# Run Elasticsearch
# For Graylog2 < 2.0.0 you need to use elasticsearch at 1.7.5 (remove the version if u use the latest version)
$ docker run --name some-elasticsearch -d elasticsearch:1.7.5 elasticsearch -Des.cluster.name="graylog2"
# Run Graylog
$ docker run --link some-mongo:mongo --link some-elasticsearch:elasticsearch -d --name="Graylog" --privileged=true -v /docker/graylog:/data:rw -v /docker/graylog:/config:rw -p 9000:9000 -p 12900:12900 -p 12201:12201 eeacms/graylog2:1.3.4.1
```

or if u want to use docker-compose, u can use this example https://github.com/eea/eea.docker.logcentral/blob/graylog-1.3.4/docker-compose.singlenode.yml

**Comment by zanardo33** [comment]
I thought that was elasticsearch 1.7.5 and MongoDB integrate contenair. 
Thank you for the answer and sorry to my lack of understanding
